### ISSUE TITLE
Documentation discrepancy over  `make run` and `make install`

### ISSUE THREAD

**Issue by tmshort** [operator-framework/operator-controller#219]
In [README.md](https://github.com/operator-framework/operator-controller/blob/main/README.md) the following is the specified behavior of `make run`:

> Run your controller (this will run in the foreground, so switch to a new terminal if you want to leave it running)

This is the README.md specified behavior of `make install`:

>Install the CRDs into the cluster

This is the `make help` of those two commands:
```
  install          Install CRDs into the K8s cluster specified in ~/.kube/config.
  run              Build the operator-controller then deploy it into a new kind cluster.
```

But in actuality, `run` build a kind cluster and then does an `install` to it, which installs the whole of operator-controller:
```
run: docker-build kind-cluster kind-load install ## Build the operator-controller then deploy it into a new kind cluster.

install: export MANIFEST="./operator-controller.yaml"
install: manifests kustomize generate ## Install CRDs into the K8s cluster specified in ~/.kube/config.
	kubectl kustomize config/default > operator-controller.yaml
	envsubst '$$CATALOGD_VERSION,$$CERT_MGR_VERSION,$$RUKPAK_VERSION,$$MANIFEST' < scripts/install.tpl.sh | bash -s
```

So, there's inconsistency, and we need to fix it. Not sure if this means we should add new targets, fix the documentation, fix the targets, or a combination.

We should also look at the `rukpak` and `catalogd` (and possibly `deppy`) to see what their targets are, so we can have consistency in the OLM ecosystem.

**Comment by joelanford** [comment]
I think `run` is consistently (or at least should be):
- Build all of my containers, create a fresh kind cluster, local the containers into the kind cluster, generate the project's install manifests (using the locally built image refs), run the project's install script.

**Comment by everettraven** [comment]
>I think run is consistently (or at least should be):
>
>    - Run code/manifest generators
>    - Build all of my container images
>    - create a fresh kind cluster
>    - load the images into the kind cluster
>    - generate the project's install manifests (using the locally built image refs)
>    - run the project's install script (refing the just-generated install manifests)

FWIW, the pattern introduced by the Makefile scaffolded with Operator-SDK and Kubebuilder is that `make run` results in running the controller binary off the cluster and follows:
>Run your controller (this will run in the foreground, so switch to a new terminal if you want to leave it running)

Taking a look at this project, it looks like it was initialized with Kubebuilder and therefore the README was auto-populated with that information since Kubebuilder also scaffolds out a README with some sections already pre-populated, one of which is the Contributing section and the quote above is included in that pre-populated output.

Totally agree that the README should be updated, just thought it would be helpful to provide some context as to the reason why it is likely incorrect :)

**Comment by tmshort** [comment]
@everettraven I believe that was the _original_ intent, even with `kubebuilder`
