### ISSUE TITLE
The Operator Controller can provide Deppy with a set of constraints and return a solution set consisting of entity IDs.

### ISSUE THREAD

**Issue by awgreene** [operator-framework/operator-controller#74]
**User Story:**
- As a Deppy user, I would like to provide Deppy a list of constraints and Entity Sources and be returned a solution set consisting of entity IDs.

**Acceptance Criteria:**
- If a solution set is found, the list of entity IDs are returned.
- If no solution set is found, an error explaining why the constraints could not be met is returned.
- The operator CR's status is updated to reflect that an entity satisfying it's constraints have been found.

**Comment by awgreene** [comment]
@joelanford this Issue focuses on the Operator Controller using the Deppy Library to to find the entity IDs so it's in the correct repository. Probably warrants a better description though.

**Comment by varshaprasad96** [comment]
This is an attempt to break down the issue and understand the implementation required to integrate with Deppy. Please correct me if I'm wrong. Also, I have a few follow up questions which would be helpful in understanding the next steps.

The process involved here is to provide Deppy with [entity sources](https://github.com/operator-framework/deppy/blob/36fa82370999fb0fa8c6a04f9fff228e58e5bc3b/pkg/deppy/input/entity_source.go#L26) and [constraint generators](https://github.com/operator-framework/deppy/blob/36fa82370999fb0fa8c6a04f9fff228e58e5bc3b/pkg/deppy/input/variable_source.go#L10) so that we can call the "DeppySolver" (https://github.com/operator-framework/deppy/blob/36fa82370999fb0fa8c6a04f9fff228e58e5bc3b/pkg/deppy/solver/solver.go#L26).

1. Entity Source - This in my mind are the list of packages which need to be installed. It includes the dependencies - for ex., prometheus-0.0.1, requires x-0.0.2, y-0.1.0 etc.
2. Constraint generator - The constraint generator needs a [variable source ](https://github.com/operator-framework/deppy/blob/36fa82370999fb0fa8c6a04f9fff228e58e5bc3b/pkg/deppy/input/variable_source.go#L10). These are basically the OLM constraints as introduced by https://github.com/operator-framework/deppy/pull/55.

The questions which I have are:
- How does the Operator Controller get the inputs for (1) and (2), given the Operator API spec only has the [package](https://github.com/operator-framework/operator-controller/blob/30416f2e09e4100437d60c2183b35d1dd8d333dc/api/v1alpha1/operator_types.go#L27) name. Do we query the bundleDeployments available (installed of rukpak provisioner) on the cluster? 
- Are the constraint generator values from FBC / Venners (https://olm.operatorframework.io/docs/reference/file-based-catalogs/#specification) and does "relatedImages" reflect the dependencies. If so, it doesn't seem like operator api has access to bundle. What is the entry point or how can the operator controller get the required inputs.

**Comment by perdasilva** [comment]
I think https://github.com/operator-framework/operator-controller/pull/101 closes this
